# Generated by Django 5.0.2 on 2024-12-10 01:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_boardpost_id_alter_comment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardPost',
            new_name='Board',
        ),
        migrations.AlterModelTable(
            name='board',
            table='blog_board',
        ),
    ]
