FROM python:3.12
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /django
COPY requirements.txt /django/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY . /django/